version: 0.0
os: linux
files:
  - source: build/libs/HolaMundo.war
    destination: /opt/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: codedeploy-scripts/stopService.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy-scripts/startService.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: codedeploy-scripts/beforeInstall.sh
      timeout: 300
      runas: root
