name: Implementa en AWS CodeDEploy

on:
  workflow_run:
    workflows: ["Lanzar stack"]
    types:
        - completed


jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-20.04
    permissions:
      contents: read

    steps:
        - uses: actions/checkout@v4

        - name: Instalar AWS CLI
          uses: aws-actions/configure-aws-credentials@v4.0.2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: "us-east-1"

        - name: Lanzar CodeDeploy
          run: |
            aws deploy create-deployment \
            --application-name "LanzarAppJavaTomcat" \
            --deployment-group-name "LanzarAppJavaTomcat" \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
